language: python
sudo: false
python:
  - "3.5"
addons:
  postgresql: "9.4"
cache: pip
install:
  - gem install sass
  - pip install psycopg2
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - psql -c 'create database lana;' -U postgres
script:
  - python manage.py lint
  - python manage.py makemigrations --check
  - coverage run manage.py test lana_dashboard.main.tests lana_dashboard.lana_data.tests
after_success:
  - coveralls
